### ISSUE TITLE
Missing compiler package from 3.4.1

### ISSUE THREAD

**Issue by decebals-btcs** [phax/jcodemodel#103]
I observe that [compiler](https://github.com/phax/jcodemodel/tree/master/src/main/java/com/helger/jcodemodel/compile) package are missing from release 3.4.1 (latest on Maven repository) and I don't understand why.
Thank you for clarification.

**Comment by phax** [comment]
The master branch is for the next major release 4.x
Please look into https://github.com/phax/jcodemodel/tree/3.4 for the 3.4 sources

**Comment by decebals-btcs** [comment]
You totally surprised me with your reaction speed. 😄 
I see a 4.0 SNAPSHOT available on maven central repository, I will try with this.
I just asking, do you have a small text regarding 3.x -> 4.x migration?

When do you think you can release the first version 4.x? (somewhat roughly).

P.S Thank you very much for the effort invested in this library, it is extremely useful !!!

**Comment by phax** [comment]
Well, you were lucky to ask a question I could easily answer ;-)
Honestly no specific plans for a new major release, as I am lacking the time to really work on it. You see it with the open pull requests... :-/ So stay with 3.4.1 - the stuff should be in, just in a different package if I am not mistaken.
