### ISSUE TITLE
Code analysis, Common subexpression elimination

### ISSUE THREAD

**Issue by leventov** [phax/jcodemodel#18]
Does the CodeModel project or particularly this fork contain any functionality like code analysis and performing simple optimizations, for exampe common subexpression elimination? If not, how do you think how difficult it could be to implement this and how friendly for such analysis/transformations the current API/library design/impl is?

**Comment by phax** [comment]
Any update on this one???

**Comment by leventov** [comment]
@phax unfortunately no, for two reasons:

 - In Java, I've found IMO better Java source model project: https://github.com/INRIA/spoon I'm using it now. Another interesting is https://github.com/square/javapoet

 - The project, I was originally implementing CSE, has moved from Java to Haskell :)

**Comment by phax** [comment]
Thanks for the update.
That means I could potentially revert your changes :)

All the best for your projects!
