### ISSUE TITLE
Add convenience method JBlock#block(boolean, boolean)

### ISSUE THREAD

**Issue by WonderCsabo** [phax/jcodemodel#29]
In #26, the behavior of `JBlock#block()` method changed in a breaking-way: now a new block is added with braces and indent. The previous behavior was adding a block with no indent and no braces.

In [AndroidAnnotations](https://github.com/excilys/androidannotations), we are using the old behavior extensively: we create no-indent no-braces blocks as placeholders, so we can easily insert code in the desired order later. To achieve this now, we have to create the blocks in the following way:
```java
JBlock block = body.block().bracesRequired(false).indentRequired(false);
```
It would be nice if the API would provide a much shorter convenience method, for example:
```java
JBlock block = body.block(false, false);
```
Or maybe this, too:
```java
JBlock block = body.blockWithoutBraces(); // with a better method name :)
```

**Comment by phax** [comment]
OK thanks. I added `block(boolean,boolean)` and `blockSimple` as `block(false,false)`. Should do the trick.

**Comment by WonderCsabo** [comment]
No need for thanks, actually i thank you for the super-fast fix! :)
