### ISSUE TITLE
Unnecessary outer block created around two simple blocks

### ISSUE THREAD

**Issue by WonderCsabo** [phax/jcodemodel#32]
The following code:

```java
JCodeModel cm = new JCodeModel();

JPackage aPkg1 = cm._package("id.myapp.activity");

JDefinedClass testClass = aPkg1._class("TestClass");

JMethod init_ = testClass.method(JMod.PUBLIC, cm.VOID, "init_");
JBlock first = init_.body().blockSimple();
JBlock second = init_.body().blockSimple();

first.decl(cm.INT, "var");
second.decl(cm.INT, "va2");

cm.build (new SingleStreamCodeWriter(System.out));
```
Generates the following:
```java
public class TestClass {

    public void init_() {
        {
            int var;
        }
        {
            int va2;
        }
    }
}
```
I do not really understand why this happening... :confused:

**Comment by WonderCsabo** [comment]
@phax i just updated my test case, which show the problem maybe not what i first thought. Indent and braces are created in the simple blocks!

**Comment by phax** [comment]
The "no indentation" and "no braces" is only in effect if there is 0 or at last 1 declaration contained in there. As soon as more than 1 decl is contained, the braces are mandatory.

**Comment by phax** [comment]
And yes, they are created by the `JBlock`

**Comment by phax** [comment]
Off topic: I asked @sviperll whether it would make sense to include his meta.java.model stuff in jcodemodel. What do you think of this?

**Comment by WonderCsabo** [comment]
OK, i understand a rational, and i know that i use blocks in a non-standard way. Maybe can i request a block type, which does not create braces and indent, ever?

**Comment by phax** [comment]
So you need something like a "VirtualBlock" that is basically just a list of declarations, statements etc. that is emitted whereever you put it - right?

**Comment by WonderCsabo** [comment]
Exactly. Of course, this virtual block could contain real blocks.

**Comment by WonderCsabo** [comment]
The easiest implementation would be adding a new flag (`neverCreateIndentBraces`) to `JBlock`, and check it when you set `m_bBracesRequired` and `m_bIndentRequired`. Then create a new block factory method which sets `neverCreateIndentBraces` to `true`.
But maybe there is a better solution. :)

**Comment by dodgex** [comment]
an option to creates a block that overrids the current behaviour would be enough.

e.g. `.blockSimple()` keeps current behaviour
and `.blockSimple(false)` does never set the required flags  (`public JBlock blockSimple(boolean requireBracesOnDecl)`)

**Comment by phax** [comment]
I added a "virtual block" mode. See `JBlock.blockVirtual()`

**Comment by WonderCsabo** [comment]
@phax thanks for your super-fast reaction, again! It was a pain to migrate to `jcodemodel` from `codemodel`, but it was worth it!
We we can expect a release containing this change?

**Comment by phax** [comment]
Very soon. I just need to check with @sviperll about the inclusion of meta and than I will release a new version. So today or tomorrow... Expect it to be 2.8.0 if the meta stuff is incorporated

**Comment by phax** [comment]
2.8.0 is released. Should be on Maven central soon. Requires Java 1.6!
