### ISSUE TITLE
Add Travis CI and snapshot deployment

### ISSUE THREAD

**Issue by WonderCsabo** [phax/jcodemodel#33]
It would be nice if this project have continuous Integration, which would also deploy a release to Sonatype OSS snapshot repo after every push to `master`.

**Comment by phax** [comment]
Can you provide the respective configuration file please. Thanks

**Comment by WonderCsabo** [comment]
I try to find some time and contribute this.

**Comment by phax** [comment]
Thanks a million

**Comment by phax** [comment]
Firts version of .travis.yml is present

**Comment by phax** [comment]
Caching is in

**Comment by phax** [comment]
SNAPSHOT deployment is in
