### ISSUE TITLE
2.8.1 release?

### ISSUE THREAD

**Issue by sviperll** [phax/jcodemodel#37]

**Comment by phax** [comment]
Will do :)

**Comment by phax** [comment]
Btw. short question: can I change the license in your provided code (.meta package) to the project license (GPL with cp exception + CDDL) or shall I leave it as is?

**Comment by sviperll** [comment]
I think it's better to change it to GPL to ease project legal status. You have my permission to relicense. As I see it there should be no problem since GPL is more restrictive than BSD.

**Comment by phax** [comment]
Thanks a lot. This helps us not getting problems in the future :)
