### ISSUE TITLE
FileCodeWriter uses PrintWriter, which in turn uses localized lineSeparator

### ISSUE THREAD

**Issue by jjYBdx4IL** [phax/jcodemodel#39]
For obvious reasons I don't want the generated java source code files to be dependent on where I execute the codemodel code. Please give me an option to set the lineSeparator manually or always use UNIX lineSeparators. TY!

**Comment by jjYBdx4IL** [comment]
Didnt check, but I guess the output encoding is according to the environment, too, then. UTF-8 + UNIX LF should be the way to go nowadays, I guess.

**Comment by phax** [comment]
Well the encoding can be provided in the `FileCodeWriter` constructor so no action needed here. By default the system encoding is used and I don't want to change this.

**Comment by phax** [comment]
A simple work around for all existing releases is to set the system property `line.separator` to the correct separator (e.g. `System.setProperty ("line.separator", "\n");`) before writing stuff out.

**Comment by phax** [comment]
`JCodeModel.setBuildingCharset (Charset)` and `JCodeModel.setBuildingNewLine (String)` should do the trick for you. Please verify and let me know if it works. If yes, I will build a new release.

**Comment by jjYBdx4IL** [comment]
Works. Nice. TY!

**Comment by phax** [comment]
Release 2.8.2 is out and soon on Maven central
