### ISSUE TITLE
Issue with JFormatter class

### ISSUE THREAD

**Issue by saxenagau** [phax/jcodemodel#45]
As of now i am using 2.8.3 API. But i am always getting an issue NullPointerIssue in the above mentioned class. When i am trying to open the class with decompiler i am getting issue as Internal Error as could you please look into the issue. As my final class is generated but there is no code inside my generated class. 

Thanks
Gaurav

**Comment by phax** [comment]
Can you please provide a sample class that causes the problem. Thanks.

**Comment by saxenagau** [comment]
Thanks Phax for quick reply i guess it due to the below line number. 
java.lang.NullPointerException
	at com.helger.jcodemodel.JFormatter.print(JFormatter.java:304)
	at com.helger.jcodemodel.JFormatter.id(**JFormatter.java:375**)
	at com.helger.jcodemodel.JMethod.declare(JMethod.java:496)

**Comment by saxenagau** [comment]
actually you are printing the value of id but i have not mentioned any id for class or method. But while printing its giving the error.

**Comment by phax** [comment]
It seems like you are creating a method without a name. I added null checks in the current HEAD version.

**Comment by saxenagau** [comment]
Thanks Phax issue got resolved. The method name which i am parsing is not coming properly from backend.

**Comment by phax** [comment]
Perfect. Happy coding :)
