### ISSUE TITLE
Normalize line endings 

### ISSUE THREAD

**Issue by WonderCsabo** [phax/jcodemodel#48]
Currently some files use Windows line endings. 

See discussion at  https://github.com/phax/jcodemodel/commit/300a18a9878b3f9b38f21695e17f5888a2cb1e5d#commitcomment-17574321

**Comment by phax** [comment]
Can you please check whether it does the trick for you now? Thanks

**Comment by WonderCsabo** [comment]
It seems so. I am using the following command to check CRLF line endings, and it returns empty:

```sh
dos2unix -ic *.* | xargs dos2unix
```

**Comment by phax** [comment]
I'm using Windows so I need to play a few tricks :)
