### ISSUE TITLE
Add option for classes to never be imported

### ISSUE THREAD

**Issue by WonderCsabo** [phax/jcodemodel#51]
In some cases, the convention for a certain class is to never be imported, but always use its fully qualified class name when referencing it or any of its members. In the Android world, such a class is the `android.R` class, which contains resource identifiers for the system, and it should not be confused with the project `R` class which gets imported. For example:
```java
package example.my.project;

public class MyActivity extends Activity {

  void someMethod() {
    String system = getString(android.R.string.some_string);
  }
}
```
It would be nice to add an option to JCodeModel to support this.

**Comment by phax** [comment]
You can use `JCodeModel.addDontImportClass` in the latest 3.0.0 SNAPSHOT (Java 8!)

**Comment by WonderCsabo** [comment]
Thanks for this! I am looking forward for the stable release. :)

**Comment by WonderCsabo** [comment]
@phax thanks again, i finally integrated this and it works as expected! 🙏
