### ISSUE TITLE
Extra semicolon when returning lambda

### ISSUE THREAD

**Issue by heruan** [phax/jcodemodel#53]
I don't know if this is a bug or I'm doing something wrong, but I can't find examples for lambdas so this is it:

```java
JMethod method = definedClass.method(...);
JLambdaMethodRef methodLambda = new JLambdaMethodRef(...);
JLambda lambda = new JLambda();
lambda.body().lambdaExpr(
    JExpr._this().invoke("getValueProvider").invoke("andThen").arg(methodLambda)
);
method.body()._return(lambda);
```
This produces:
```java
public default StringFilter<T> description() {
    return () -> this.getValueProvider().andThen(Category::getDescription);
    ; // <- Unreachable code error!
}
```
with the extra `;` resulting in an "Unreachable code" error in Eclipse. How can I avoid the extra semicolon?

**Comment by phax** [comment]
You are using version 2.8.6 or 3.0.0 SNAPSHOT?

**Comment by heruan** [comment]
Thank you for the (impressive) responsiveness! I'm on 2.8.6 from Maven Central, but if you have a snapshot repository I'll try 3.0.0 right away.

**Comment by phax** [comment]
NP. 3.0.0 requires Java 8 - is this a problem?

**Comment by heruan** [comment]
Absolutely not, the project's 1.8 -> 1.8. Does 3.0.0 already address this?

**Comment by phax** [comment]
I'm not sure :) Just want to know whether I potentially need a backport or whether I can check in the latest only :) - give me a few minutes....

**Comment by heruan** [comment]
I managed to test it with current 3.0.0 and the output is the same: extra semicolon.

**Comment by phax** [comment]
I saw it. There are multiple issues to address. While creating your test cases I saw that there was no way to invoke a Lambda if stored in a variable.... Stay tuned

**Comment by phax** [comment]
Sorry - no solution today :( I don't have too much time right now, but will address it asap

**Comment by phax** [comment]
Well I proved myself wrong - now working. Please cross check - Travis build should be available soon

**Comment by heruan** [comment]
Awesome, it works! Hope to see the fix on a Maven release soon. Thank you very much!
