### ISSUE TITLE
API docs: 3.0.0 missing, olders miss Maven output

### ISSUE THREAD

**Issue by GitMensch** [phax/jcodemodel#55]
README.md links to http://phax.github.io/jcodemodel/

* 3.0.0 missing completely
* 2.7.11 and 2.8.0 have a link "Have a look at the Maven site output" which results in HTTP Error 404 "not found" (it exists for 2.7.8-SNAPSHOT)

**Comment by phax** [comment]
Thanks for the reminder!

**Comment by phax** [comment]
* 3.0.0 is now contained
* Replaced 2.8.0. with 2.8.6 as the latest 2.8.x release
* Kicked 2.7.8 as 2.7.11 as the latest 2.7.x release is contained
