### ISSUE TITLE
Construct JLambdaMethodRef with JInvocation

### ISSUE THREAD

**Issue by heruan** [phax/jcodemodel#56]
I need to generate this field signature:

```java
public final StringFilter<E> firstName = this.andThen(Person::getFirstName)::apply;
```

I can easily generate the `this.andThen(Person::getFirstName)` part with:

```java
JLambdaMethodRef lambdaMethod = new JLambdaMethodRef(personType, getterName);
JInvocation jInvocation = JExpr._this().invoke("andThen").arg(lambdaMethod);
```

but I can't generate a lambda method reference from this `JInvocation`, since I can't construct a `new JLambdaMethodRef(jInvocation, "apply")` nor I can generate a lambda reference with any `JInvocation` method, e.g. `jInvocation.ref("apply")` generates `.apply` instead of `::apply`.

**Comment by phax** [comment]
I will add a test and complete the API before the release. Will be today or tomorrow!
