### ISSUE TITLE
JDefinedClass.getMethod does not work when a parameter is JDirectClass

### ISSUE THREAD

**Issue by fbaro** [phax/jcodemodel#58]
The `JDefinedClass.getMethod()` method works by searching a method with matching name and parameter types. As `JDirectClass` does not implement the `equals` method, if `getMethod()` is provided with a `JDirectClass` freshly obtained from `JCodeModel.ref()`, it will not return the required method.

**Comment by phax** [comment]
Thanks for this. I added hashCode
