### ISSUE TITLE
chained invoke is not applied

### ISSUE THREAD

**Issue by guiguilechat** [phax/jcodemodel#63]
here is my code. I am using jcodemodel 3.0.4

```

JLambda lambdaSet = new JLambda();
JLambdaParam arr = lambdaSet.addParam("arr");
JBlock setBody = lambdaSet.body().synchronizedBlock(holder).body();
(..)
setBody.invoke(holder, "entrySet").invoke("retainAll").arg(newmap.invoke("entrySet"));
```
[source](https://github.com/guiguilechat/JCELechat/blob/3be01215cf540e99f1eb11cbe39fada5910cbb4f/model/esi/ESI-compiler/src/main/java/fr/guiguilechat/jcelechat/model/esi/PathTranslator.java)

this is what is produced (inside the synchronized)

`holder.entrySet();`
code example is [here](https://github.com/guiguilechat/JCELechat/blob/50f7b0a9d9750d2954bb442d8389f1d5da078bf0/model/esi/ESI/src/generated/java/fr/guiguilechat/jcelechat/model/esi/compiled/disconnected/Sovereignty.java)

I expected 

`holder.entrySet().retainAll(newmap.entrySet());`

IT seems that chaining invoke() results in only the first one being added to the block.

**Comment by phax** [comment]
It's a general problem, not just in Lambdas - will look at it

**Comment by phax** [comment]
There is a nifty little difference between the following:
```java
setBody.invoke (holder, "entrySet").invoke ("retainAll").arg (arr.invoke ("entrySet"));
```
and
```java
setBody.add (JExpr.invoke (cm, holder, "entrySet").invoke ("retainAll").arg (arr.invoke ("entrySet")));
```
The first version creates an invocation inside the `setBody` and returns it. Any change to this is not store in the `setBody`.

The second version first builds the whole chain, and than adds it to thesetBody.

The best way to resolve this issue whould imho be, to change the return type of `JBlock.invoke` to `void`, to avoid that this happens again. This would however be a breaking change and require 3.1.0. Any objections?

**Comment by guiguilechat** [comment]
That's too bad, the invoke() chain is easier to read IMO.
What's more changing it to void would invalidate the second version too :/

**Comment by phax** [comment]
Chaining is okay. But there is a difference in `block.invoke (...).invoke ()` (which does not work) and `block.add (invoke (...).invoke (...).invoke (...))` which does work.
I would just `void` the `block.invoke (...)` method.

**Comment by guiguilechat** [comment]
I just look the code.

Right now, block.invoke(a).invoke(b).invoke(c) creates a tree of invokes : 
```
inva = block.invoke(a)
invb = inva.invoke(b) // = jexpr.invoke(inva, b)
invc = invb.invoke(c) //= jexpr.invoke(invb, c) = jexpr.invoke(jexpr.invoke(inva, b), c)
```
the matter is that block.invoke only adds inva to the block, not invc ; thus invc becomes orphan.
To ad invc instead, I propose to rotate the jexpr tree in the Jinvocation.invoke, so that  the call becomes
```
inva.invoke(b) {
  inva.righexpr = jexpr.invoke(inva.rightexpr, b);
  return this
}
```

and thus, return this in the invoke() instead of a new jinvocation.

**Comment by guiguilechat** [comment]
but yeah, the void block.invoke() seems the easiest solution( and so the less bug prone)

**Comment by phax** [comment]
That is a very constructive proposal. But would that cause issues on the order of invocation for existing code? And not all invocations are binary (as constructor calls)... I'm basically afraid to change internals like this :(

Okay - just saw your second comment. I will provide a SNAPSHOT asap and you can check.

**Comment by guiguilechat** [comment]
I am also very afraid of my proposal to actually break more things that it fixes ^^ .

Instead of voiding block.invoke, maybe deprecate it ? I'm still convinced my proposal is the best on long term, just it requires a lot of testing, small steps. Deprecating block.invoke() should not require a change of version.

**Comment by phax** [comment]
It actually effects 11 overloads in `JBlock` - `invoke`, `invokeThis`, `invokeSuper`, `staticInvoke` and `_new`.
Deprecating is also not was is desired. The idea is to simplify the code a bit, and for "ony" passing arguments it works fine. 
I now extended the API in a way, so that all `block.X (...)` methods can be easily replaced with `block.add (JExpr.X (...))`

**Comment by guiguilechat** [comment]
my bad, I was actually using 3.0.3 (had not updated maven project).

I confirm that replacing the chain by body.add(JExpr.invoke(a).invoke(b)) works for me alright :)

**Comment by phax** [comment]
Okay thanks. I will release 3.1.0 asap

**Comment by phax** [comment]
http://repo2.maven.apache.org/maven2/com/helger/jcodemodel/3.1.0/
