### ISSUE TITLE
add no-param "value" for annotation.

### ISSUE THREAD

**Issue by guiguilechat** [phax/jcodemodel#64]
Hello.

When I annotate eg a field with an annotation.
If this annotation accept one parameter which has name "value".
I can use this annotation with `@annotation(myvalue)`

In JCM  I need to specify a name in the annotation. However, if I specify "value" it generates the correct expected result.
Could we have another function `/** add a value to the default parameter of the annotation*/JAnnotationUse#param(String value){return param("value", value);}`

I guess the issue is, that there are already many different methods for param(), eg with String, double, etc.

**Comment by phax** [comment]
Sure no problem. I will create an overload for all types.

**Comment by phax** [comment]
Contained in 3.2.0

**Comment by guiguilechat** [comment]
you can close automatically the issue by using eg "fixed #64" in the comment of your commit.
I learnt that recently
https://help.github.com/articles/closing-issues-using-keywords/
