### ISSUE TITLE
add @deprecated explanations

### ISSUE THREAD

**Issue by guiguilechat** [phax/jcodemodel#65]
Hello.

Last time you deprecated some chained method in jbblock, also the JCodemodel.write() . First one had to call the JBlock.add(Jexpr.X) and wirte is now I think in a dedicated class. All is good.
However I had a hard time getting what I exactly had to do to correct my code.

Could you, whenever a method is deprecated, refer to the issue and the correction in the javadoc ?
as recommanded in https://docs.oracle.com/javase/1.5.0/docs/guide/javadoc/deprecation/deprecation.html#how 

> You are strongly recommended to use the Javadoc @deprecated tag with appropriate comments explaining how to use the new API. This ensures developers will have a workable migration path from the old API to the new API. For more information, see Using the @deprecated Javadoc Tag.

**Comment by phax** [comment]
Thanks for outlining this. Hope this is okay now.

**Comment by guiguilechat** [comment]
Just looked at the commit and seems nice :) :+1: 

Sorry to be this pedantic, it's difficult to take back a project and not remember why those calls are deprecated and what I should do to use next release correctly .

**Comment by phax** [comment]
You are absolutely right - usually I try to do that. Thanks for being pedantic :D
