### ISSUE TITLE
Migrate off of jsr305

### ISSUE THREAD

**Issue by ptahchiev** [phax/jcodemodel#69]
As discussed here:

google/guava#2960

and here:

spotbugs/spotbugs#180

JSR305 is dead and further more any jar that has classes in java or javax packages violates the Oracle JVM redistribution license.

Please use the spotbugs annotations instead.

**Comment by phax** [comment]
So you suggest to use https://search.maven.org/artifact/com.github.spotbugs/spotbugs-annotations/4.0.0-beta4/jar ?
Guava goes for the Checker Framework? Why not this one?

**Comment by ptahchiev** [comment]
I don't see any problem with either of those. I think spotbugs is very well known and a lot of people are already using it so it will not bring them an extra dependency.

**Comment by phax** [comment]
spotbugs-annotations transitively depends on jsr305 annotation - I don't see the benefit here 🤷‍♂

**Comment by phax** [comment]
@ptahchiev you can see it here: https://github.com/spotbugs/spotbugs/blob/master/spotbugs-annotations/build.gradle - so I hope it's okay, it don't make a change atm
