### ISSUE TITLE
[proposal] check class name against keywords and java.lang

### ISSUE THREAD

**Issue by guiguilechat** [phax/jcodemodel#71]
# Keywords

see #70 for the keywords 

# java.lang

## Issue 

This is an issue because this package is already imported and as such not referenced to.

Typically if I create a my.package.Object class and then I create a method 

    @Override
    boolean equals(java.lang.Object other) 

The object other actually refers to the class I am crating, and not the java.lang.Object class.
This issue literally happened to me when compiling against a openapi web service that produces "Object" responses.

## Detection

This issue is very complicated : since the java reflection works bottom-up, that is the classes know their package but the package doesn't know its classes, it's difficult to find if the class exists without a java.lang.class.forName("java.lang."+sName), with trycatch around. This expensive call requires to cache the result in a hasmap<String, Boolean>

here is my code

	private static final HashMap<String, Boolean> resolvedJavaLangNames = new HashMap<>();
	
         /**
	 * check if a name already represents a class in the java.lang package. eg
	 * String should return true, but LeetH4X0R should not.
	 * 
	 * @param className
	 *          name to test
	 * @return the existence of such a class in the java.lang (cached)
	 */
	public static boolean isJavaLangClass(String className) {
		if (resolvedJavaLangNames.containsKey(className)) {
			return resolvedJavaLangNames.get(className);
		}
		boolean isJavaLang = true;
		try {
			Class.forName("java.lang." + className);
		} catch (Exception e) {
			isJavaLang = false;
		}
		resolvedJavaLangNames.put(className, isJavaLang);
		return isJavaLang;
	}

Looking at how fast it is to use JCodeModel, I consider the use of synchronization to be worthless (I usually don't and thus would have synced over the hashmap in the method)

It should check for specific exception (security exception means I can't tell)

## Reaction

In the case the class C is in java.lang already, two possibilities : 
- internally mark the class C as javaLangMisleading, so that all call to a java.lang.C are specifically written as such
- throw an exception (bad - unless in the option)

IMO both should be available. mark the class C as misleading , AND allow users to avoid this with a compilation option.

Especially, I'm not sure how to make the misleading part, since the writing of the class names may be done without the knowledge of where that name is used.

**Comment by glelouet** [comment]
in the specific case of refering to java.lang.Object it's an issue, not an enhancement.

**Comment by phax** [comment]
Makes total sense. Thanks for pointing this out. Part of 3.3.0 release

**Comment by glelouet** [comment]
I will make more of an example of what should compile correctly, gimme some more time.

**Comment by phax** [comment]
It does it, but the other way around:
```java
package jcodemodel;

public class MyClass {

    public void call(Object obj) {
    }

    public void call(MyClass.Object obj) {
    }

    public void call(Number obj) {
    }

    public void call(MyClass.Number obj) {
    }

    public static class Number {
    }

    public static class Object {
    }
}
```
That is semantically equivalent I think ok....

**Comment by glelouet** [comment]
No because the java compiler will refuse to compile it. Number and Myclass.Number are equivalent in those cases, therefore you have two methods with the same signature.

That's why I gave the link to the memory compiler, because it shows that the compilation of the generated classes fails.

**Comment by glelouet** [comment]
here is the code that shows this : 
```

@Test
	public void testBadPackage() throws JClassAlreadyExistsException, ClassNotFoundException {
		JCodeModel cm = new JCodeModel();
		JDefinedClass myclass = cm._class(JMod.PUBLIC, "mypck.MyClass");
		JDefinedClass myObject = myclass._class(JMod.PUBLIC | JMod.STATIC, "Object");
		myclass.method(JMod.PUBLIC, cm.VOID, "call").param(Object.class, "obj");
		myclass.method(JMod.PUBLIC, cm.VOID, "call").param(myObject, "obj");

		DynamicClassLoader dcl = DynamicClassLoader.generate(cm);
		dcl.findClass(myclass.fullName());
	}
```

Here is the output result : 

>  compile diagnostic /mypck/MyClass.java:8: error: method call(mypck.MyClass.Object) is already defined in class mypck.MyClass
>     public void call(MyClass.Object obj) {

**Comment by phax** [comment]
Ah okay - got it. I will check the dynamic compilation thingy separate...
New version creates:
```java
package jcodemodel;

public class MyClass {

    public void call(java.lang.Object obj) {
    }

    public void call(MyClass.Object obj) {
    }

    public void call(java.lang.Number obj) {
    }

    public void call(MyClass.Number obj) {
    }

    public void call(Byte obj) {
    }

    public void call(Long obj) {
    }

    public static class Number {
    }

    public static class Object {
    }
}
```

**Comment by glelouet** [comment]
Note that if you can fix that quickly, there is no point failing when the user requests to create an Object class anymore.
I just thought that making it work correctly could request too much time.

Ideally you want the previous result to replace the Myclass.Number by Number, because then MyClass.number is the highest priority in the resolution.
