### ISSUE TITLE
https://github.com/eclipse-ee4j/jaxb-ri 

### ISSUE THREAD

**Issue by gitmotte** [phax/jcodemodel#73]
The original codemodel project is maintained now at https://github.com/eclipse-ee4j/jaxb-ri 
Not sure where the differences are between
* https://github.com/eclipse-ee4j/jaxb-ri - https://mvnrepository.com/artifact/org.glassfish.jaxb/codemodel/2.3.2 (2019)
* https://mvnrepository.com/artifact/com.sun.codemodel/codemodel/2.6 (2011)

What was the base of your fork?
* https://github.com/phax/jcodemodel  -https://mvnrepository.com/artifact/com.helger/jcodemodel/3.2.4 (2019)
Would you contribute your work to eclipse-ee4j ?

**Comment by phax** [comment]
Of course I would contribute the work to eclipse-ee4j. Its just nearly 6 year of deviation, so I guess this is not something we merge in an afternoon :D
If you are affiliated with the Eclipse guys - how to tackle this?

**Comment by phax** [comment]
I think this ship has sailed - the differences are too huge and I really don't want to take the effort. If anyone is motivated, I'm happy to assist here and there.
