### ISSUE TITLE
in-memory and jar/zip platform

### ISSUE THREAD

**Issue by guiguilechat** [phax/jcodemodel#79]
follow #74 

Should create platform file specifications in EFileSpecification for JAR/ZIP and in-memory file systems. Those platform specs would allow to create files that match the restriction of their respective file system.

JAR is used eg to distribute the source files of a project. Can also be used to export the .class files though this is not really the use of JCodeModel. The specification is [here](https://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs/14759913#14759913) 

Inmemory is used to directly compile the .java files into the .class files, which can then be placed in another file system, or fed to a ClassLoader . I don't know the limitations of such a system, should work on them.

priority : very low.

**Comment by guiguilechat** [comment]
if the jar/zip is not useful, maybe close since the inmemory is done ?

**Comment by phax** [comment]
As the interest in it seems limited I would suggest to close this one for now.
