### ISSUE TITLE
Enum constant arg with class

### ISSUE THREAD

**Issue by robertomorati** [phax/jcodemodel#86]
Hi @phax 

I faced with an "unusual" situation, where I need to pass a Class as a parameter in a constant enum. In other words, something like that:

`ERRO_SQL("900","System Error", MonitoringKeySQL.class)`

I have defined `JDefinedClass monitoringKeySQL= createJDefinedClass("package.MonitoringKeySQL");`

`enums.arg(<class here???>);`

Please, could help me with this situation?

All the best,

**Comment by phax** [comment]
Try `cm.ref("package.MonitoringKeySQL").dotClass()`

**Comment by robertomorati** [comment]
Hi @phax 

Thank you for your help.

With that, I receive:
The method dotClass() is not defined for the type AbstractionJClass.

I need to generate a constant enum passing a class in arg. For instance,  String.class or  MonitoringKeySQL.class.

**Comment by phax** [comment]
What version are you using?
With the latest version this my output for the test case:
```java
package issue86;

public class Issue86Test {

    public enum MyEnum {
        A(String.class),
        C(null);
    }
}
```

**Comment by robertomorati** [comment]
Hi @pahx.

That's worked. 
Really sorry, was my mistake, because I migrated from old jcodemodel (org.glassfish.jaxb).
I tried to delete my message, but it wasn't fast enough XD

I really appreciate your attention and great job!!
All the est!!
