### ISSUE TITLE
Generate  *.class

### ISSUE THREAD

**Issue by robertomorati** [phax/jcodemodel#87]
@phax 

How are you doing?

Please, could you tell me if it's possible to generate a .class file instead of .java file?

All the best,
Roberto Morati

**Comment by phax** [comment]
Hi Roberto,
It's not possible. You can only create ".java" files and than you need to compile them separately.
There is no build-in compilation - sorry.
BR, Philip

**Comment by glelouet** [comment]
I think you can with the PR I made(dynamic class loader). Not sure though.

**Comment by robertomorati** [comment]
@glelouet 

We have a maven plugin with a goal generate that generated some java files.
Now I'm trying to update that goal to generate class with those java files.

First, I tried to generate those classes running the command line in java code, but one file depends on other files, so its crashes. 
Now, I studying about addCompileSourceRoot inside execute() of a goal, but it didn't work.

**Comment by robertomorati** [comment]
@glelouet I solved it using javac with wildcard (*) and sourcepath.

**Comment by phax** [comment]
Ok @robertomorati  The upcoming version 4.0 will have ht epossibility to directly compile the created CodeModel classes when you are using a JDK. hat would simplify your process I assume
