### ISSUE TITLE
Inner Class

### ISSUE THREAD

**Issue by robertomorati** [phax/jcodemodel#88]
Hi @phax 

Could you help me with another issue?

How to create an Inner class with my scenario, follow (?):

```
public class Foo extends  RuntimeException {​​​​​
  public static class InnerFoo extends Foo{​​​​​
    
  }​​​​​
}​​​​​
```

Thank you so much,

**Comment by phax** [comment]
The unit test https://github.com/phax/jcodemodel/blob/master/src/test/java/com/helger/jcodemodel/InnerClassFuncTest.java is your friend here.
The outcome of this test is:
```java
package org.test;

public class DaTestClass {

    public DaTestClass.Inner getInner() {
    }

    public DaTestClass.Inner.InnerInner getInnerInner() {
    }

    public DaTestClassInner getInner2() {
    }

    public DaTestClassInner.Inner2 getInner2Inner() {
    }

    public class DaTestClassInner {

        public class Inner2 {
        }
    }

    public class Inner {

        public class InnerInner {
        }
    }
}
```
and
```java
package org.test;

import org.test.DaTestClass.DaTestClassInner;

public class OtherClass {

    public DaTestClass.Inner getInner() {
    }

    public DaTestClass.Inner.InnerInner getInnerInner() {
    }

    public DaTestClassInner.Inner2 getInner2Inner() {
    }

    public DaTestClass getOuter() {
    }
}
```

Happy coding

**Comment by glelouet** [comment]
Is there a FAQ ? Or a example project to let people have a glance at those use cases ?

**Comment by phax** [comment]
No, there is no Wiki yet.
I could create one, but would need input from the community but I don't have the resources to provide the full content on my own. So if there are some volunteers that would help :)

**Comment by phax** [comment]
@glelouet I started at https://github.com/phax/jcodemodel/wiki/How-Tos - I hope this approximately what you were looking for

**Comment by glelouet** [comment]
you rock :)

**Comment by glelouet** [comment]
can you make a second project, phax/jcodemodel-examples ? Should be a pom.
that way we can make examples in the example1/src/main/java and they will be automatically compiled to example1/src/generated/java. This is, to avoid having a huge page of examples. Instead you just link those examples source and generated files ; also this way the code will be always up to date as long as the jcodemodel-examples is redeployed.

**Comment by phax** [comment]
Well it has pros and cons - when linking to the examples, than it means, that the code is not visible on a single page - than you need to jump back and forth.
On the other hand when having a test project that means, that we can always verify the examples are compiling. Hmmm....

**Comment by glelouet** [comment]
your choice, just a suggestion.
